# Generated by Django 4.2.15 on 2024-09-23 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("v1_sessions", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="participant",
            name="role",
            field=models.CharField(default=None, max_length=100, null=True),
        ),
    ]
