# Generated by Django 4.2.15 on 2024-09-12 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("v1_sessions", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="patsession",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
