# Generated by Django 4.2.15 on 2024-09-23 06:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("v1_sessions", "0002_participant_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="participant",
            name="session_deleted_at",
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AddField(
            model_name="patsession",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="decision",
            name="session",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="session_decision",
                to="v1_sessions.patsession",
            ),
        ),
        migrations.AlterField(
            model_name="participant",
            name="session",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="session_participant",
                to="v1_sessions.patsession",
            ),
        ),
        migrations.AlterField(
            model_name="participantdecision",
            name="decision",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="decision_participant",
                to="v1_sessions.decision",
            ),
        ),
        migrations.AlterField(
            model_name="participantdecision",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_participant_decision",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
