# Generated by Django 4.2.15 on 2024-09-27 12:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("v1_sessions", "0004_patsession_notes"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="participantdecision",
            name="user",
        ),
        migrations.AddField(
            model_name="participantdecision",
            name="desired",
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AddField(
            model_name="participantdecision",
            name="organization",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="organization_participant_decision",
                to="v1_sessions.organization",
            ),
        ),
        migrations.AlterField(
            model_name="organization",
            name="acronym",
            field=models.CharField(default=None, max_length=25, null=True),
        ),
    ]
