# Generated by Django 4.2.15 on 2024-11-12 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("v1_sessions", "0006_participantcomment"),
    ]

    operations = [
        migrations.RenameField(
            model_name="patsession",
            old_name="other_sector",
            new_name="other_purpose",
        ),
        migrations.RemoveField(
            model_name="patsession",
            name="sector",
        ),
        migrations.AddField(
            model_name="patsession",
            name="purpose",
            field=models.IntegerField(
                choices=[
                    (1, "Purpose of creation #1"),
                    (2, "Purpose of creation #2"),
                    (3, "Purpose of creation #3"),
                    (4, "Purpose of creation #4"),
                    (5, "Purpose of creation #5"),
                    (6, "Purpose of creation #6"),
                    (7, "Purpose of creation #7"),
                    (8, "Purpose of creation #8"),
                    (9, "Purpose of creation #9"),
                    (10, "Purpose of creation #10"),
                    (0, "Other"),
                ],
                default=None,
                null=True,
            ),
        ),
    ]
