# Generated by Django 4.2.15 on 2024-09-10 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("v1_users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="systemuser",
            name="reset_password_code",
            field=models.UUIDField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="systemuser",
            name="reset_password_code_expiry",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
