# Generated by Django 4.2.15 on 2024-11-12 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("v1_users", "0002_systemuser_reset_password_code_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="systemuser",
            name="account_purpose",
        ),
    ]
