# Generated by Django 4.2.15 on 2024-11-13 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("v1_users", "0003_remove_systemuser_account_purpose"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="systemuser",
            name="gender",
        ),
    ]
